python3 ../../../main_linear.py \
    --dataset cifar100 \
    --backbone resnet18 \
    --data_dir ./datasets \
    --train_dir "cifar100/train" \
    --val_dir "cifar100/val" \
    --max_epochs 100 \
    --gpus 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --warmup_epochs 5 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 4 \
    --save_checkpoint \
    --name simsiam-cifar100-linear-eval-momentum99-subset1 \
    --pretrained_feature_extractor "../../pretrain/cifar/trained_models/simsiammom/simsiam-cifar100-momentum99_subset1/simsiam-cifar100-momentum99_subset1-simsiam-cifar100-momentum99_subset1-ep=199.ckpt" \
    --project ssl-project \
    --entity cu-ssl-project \
    --checkpoint_dir "trained_models/linear/28xhd93h" \
    --resume_from_checkpoint "trained_models/linear/28xhd93h/simsiam-cifar100-linear-eval-momentum99-subset1-28xhd93h-ep=99.ckpt" \
    --output_dir results \
    --predict
    #--wandb \
