python3 ../../../main_linear.py \
    --dataset cifar100 \
    --backbone resnet18 \
    --data_dir ./datasets \
    --train_dir "cifar100/train" \
    --val_dir "cifar100/val" \
    --max_epochs 100 \
    --gpus 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --warmup_epochs 5 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 2 \
    --name simclr-cifar100-linear-eval-mom98-99-momencoder \
    --pretrained_feature_extractor "../../pretrain/cifar/trained_models/simclrmom/simclr-cifar100-momentum98-99/simclr-cifar100-momentum98-99-simclr-cifar100-momentum98-99-ep=199.ckpt" \
    --project ssl-project \
    --entity cu-ssl-project \
    --use_momentum_backbone \
    --wandb \
